In [12]:
#q1
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],
        'Feature2': [5.5, 6.7, 8.9]}
df = pd.DataFrame(data)
print(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')
# ValueError: invalid literal for int() with base 10: 'Thirty'
# on executing line 7 while converting to int datatype the string "thirty" cannot be converted to int
# convert invalid data to valid one. Source : https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html
print("=============")
print(df)

{'Feature1': ['10', '20', 'Thirty'], 'Feature2': [5.5, 6.7, 8.9]}
   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [9]:
#q2
import pandas as pd


data = {'A': [1, 2, None],
        'B': [4, None, 6]}
#print(data)
df = pd.DataFrame(data)
#print(df.mean())
out_mean_value = df.mean()
df.fillna(out_mean_value)
# NAN cannot be considered as data. so use inplace flat in df.fillna method. source: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
print(df)


{'A': [1, 2, None], 'B': [4, None, 6]}
A    1.5
B    5.0
dtype: float64
     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0


In [20]:
#q3
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Reshape X to be 2D with 5 samples and 1 feature source : https://stackoverflow.com/questions/51150153/valueerror-expected-2d-array-got-1d-array-instead
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
#LinearRegression model should be imported
model.fit(X, y)
print(model.predict([[6]]))

[12.]


In [18]:
#q4
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1) # Error: Should be 2D# Reshape X to be 2D with 5 samples and 1 feature source : https://stackoverflow.com/questions/51150153/valueerror-expected-2d-array-got-1d-array-instead

out_scaler = StandardScaler()
out_scalerscaled_data = out_scaler.fit_transform(data)

print(out_scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [23]:
#q5
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
#y = ['yes', 'no', 'yes']   this is not good for prediction as it is in string, numeric needed
y = [1, 0, 1]

model = LogisticRegression()
model.fit(X, y)
print(model.predict([[4, 5]]))

[1]


In [26]:
#q6
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
# encoder = OneHotEncoder() error due to 2d conversion, can use sparse arugment
out_encoder = OneHotEncoder(sparse_output=False) # library Changed 'sparse' to 'sparse_output'_      x
out_encoded = out_encoder.fit_transform(df[['Category']])

print(out_encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [28]:
#q7
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]
#print("b4 x_train:", X_train)
#print("b4 y_train:", y_train)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("after X_train:", X_train)
print("after y_train:", y_train)
#x values y values didnt reach expectation of sample values


after X_train: [[3, 4], [5, 6], [7, 8]]
after y_train: [1, 0, 1]


In [29]:
#q8
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]

encoder_final = LabelEncoder()
y_train_encoded_exc = encoder_final.fit_transform(y_train)

model = LogisticRegression()
#print("model -> ")
#print(model)
model.fit(X_train, y_train_encoded_exc)

print(model.predict([[2, 3]]))
#labels are in string, numeric is required when it comed to regression logistics

[1]


In [30]:
#q9
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

import numpy as np
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

# data has missing values, nan cannot be considered for regression. values may be replaced with minimum mean value
imputer = SimpleImputer(strategy="mean")
X_train_imputed = imputer.fit_transform(X_train)
model = LinearRegression()
model.fit(X_train_imputed, y_train)


prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)

Predicted Output: [20.]


In [35]:
#q11
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # model predicting wrongly as string cannot be considered for classifier. string to be converted to numeric

encoder = LabelEncoder()
y_train_fina = encoder.fit_transform(y_train)

model = DecisionTreeClassifier()
model.fit(X_train, y_train_fina)
print(model.predict([[2, 3]]))

[1]


In [46]:
#q12
X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]


#model.fit(X_train, y_train)
#print(model.predict([[1, 150]]))
#has to normalize the output because the out is not relaibale. preprocessing model can improve model performance

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform([[1, 150]])
print(model.predict(X_test_scaled))

[0]
